from __future__ import annotations

import json
from dataclasses import asdict

from sqlalchemy import text

from .db import engine
from .ingestion import IngestionManifest


def persist_manifest(manifest: IngestionManifest) -> str:
    """Persist an ingestion manifest idempotently by SHA-256.

    The deterministic dataset UUID generated by the ingestion layer is used as
    the database primary key for a new dataset. Re-uploading identical content
    resolves to the same UUID and refreshes metadata without duplicating data.
    """
    with engine.begin() as conn:
        row = conn.execute(
            text(
                """
                INSERT INTO datasets(id, name, source_type, original_filename, sha256, status, metadata)
                VALUES (CAST(:id AS uuid), :name, 'zip_upload', :filename, :sha256, 'validated', CAST(:metadata AS jsonb))
                ON CONFLICT (sha256) DO UPDATE SET
                    original_filename = EXCLUDED.original_filename,
                    status = 'validated',
                    updated_at = now()
                RETURNING id
                """
            ),
            {
                "id": manifest.dataset_id,
                "name": manifest.original_name,
                "filename": manifest.original_name,
                "sha256": manifest.sha256,
                "metadata": json.dumps({"ingestion_version": "0.1.0"}),
            },
        ).mappings().one()
        dataset_id = str(row["id"])

        for asset in manifest.assets:
            conn.execute(
                text(
                    """
                    INSERT INTO dataset_assets(dataset_id, path, extension, size_bytes, row_count, columns, metadata)
                    VALUES (CAST(:dataset_id AS uuid), :path, :extension, :size_bytes, :row_count, CAST(:columns AS jsonb), '{}'::jsonb)
                    ON CONFLICT (dataset_id, path) DO UPDATE SET
                        extension = EXCLUDED.extension,
                        size_bytes = EXCLUDED.size_bytes,
                        row_count = EXCLUDED.row_count,
                        columns = EXCLUDED.columns
                    """
                ),
                {
                    "dataset_id": dataset_id,
                    "path": asset.path,
                    "extension": asset.extension,
                    "size_bytes": asset.size_bytes,
                    "row_count": asset.rows,
                    "columns": json.dumps(asset.columns or []),
                },
            )

        conn.execute(
            text(
                """
                INSERT INTO ingestion_events(dataset_id, stage, status, message, payload)
                VALUES (CAST(:dataset_id AS uuid), 'zip_validation', 'success', :message, CAST(:payload AS jsonb))
                """
            ),
            {
                "dataset_id": dataset_id,
                "message": f"Validated {len(manifest.assets)} supported assets",
                "payload": json.dumps(asdict(manifest)),
            },
        )

    return dataset_id
